spring.application.name=WritingMitra
#server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/writing_mitra_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

#it will help to directly ive instructio in my sql from spring framework
spring.jpa.hibernate.ddl-auto=update

#if we write validate in place of update it will not make any new table only change in exsisting table
spring.jpa.show-sql=true
